### ISSUE TITLE
Remover linhas em branco vindas da spreadsheet

### ISSUE THREAD

**Issue by gcgbarbosa** [notific-com-br/notific-com-br.github.io#7]
Quando baixamos o arquivo tsv com o axios, as vezes o google spreadsheet detecta linhas em branco como sendo preenchidas e as poe no arquivo baixado atravez da api.
Como o codigo atualmente pega a ultima linha da tabela, isso faz com que os dados impressos saiam em branco.

**Comment by annielmenezes** [comment]
Eu codifiquei uma tratativa para isso. Vou sumir com o novo gráfico.

**Comment by annielmenezes** [comment]
Pull request sanitiza os dados antes de exibir os dados #8

**Comment by gcgbarbosa** [comment]
Toppp, quando a gente fizer o merge eu fecho.
